name: CI/CD Status

on:
  workflow_run:
    workflows: ["Android CI", "Release", "Supabase Deploy", "Check Supabase Config"]
    types:
      - completed
  workflow_dispatch:  # 添加手动触发选项

jobs:
  update-status:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Update README with build status
      run: |
        # 获取最新的工作流状态
        ANDROID_CI_STATUS=$(curl -s -H "Authorization: token ${{ github.token }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/workflows/android.yml/runs?per_page=1" | \
          jq -r '.workflow_runs[0].conclusion')
        
        RELEASE_STATUS=$(curl -s -H "Authorization: token ${{ github.token }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/workflows/release.yaml/runs?per_page=1" | \
          jq -r '.workflow_runs[0].conclusion')
        
        SUPABASE_STATUS=$(curl -s -H "Authorization: token ${{ github.token }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/workflows/supabase-deploy.yml/runs?per_page=1" | \
          jq -r '.workflow_runs[0].conclusion')
        
        SUPABASE_CONFIG_STATUS=$(curl -s -H "Authorization: token ${{ github.token }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/workflows/check-supabase-config.yml/runs?per_page=1" | \
          jq -r '.workflow_runs[0].conclusion')
        
        # 更新README.md中的构建状态
        sed -i '/## 构建状态/,/## /c\
        ## 构建状态\n\
        \n\
        | 工作流 | 状态 |\n\
        |-------|------|\n\
        | Android CI | ![Android CI](https://github.com/${{ github.repository }}/actions/workflows/android.yml/badge.svg) |\n\
        | Release | ![Release](https://github.com/${{ github.repository }}/actions/workflows/release.yaml/badge.svg) |\n\
        | Supabase Deploy | ![Supabase Deploy](https://github.com/${{ github.repository }}/actions/workflows/supabase-deploy.yml/badge.svg) |\n\
        | Supabase Config | ![Supabase Config](https://github.com/${{ github.repository }}/actions/workflows/check-supabase-config.yml/badge.svg) |\n\
        \n\
        ' README.md
        
        # 如果有变更，提交更改
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add README.md
        git commit -m "Update build status badges [skip ci]" || echo "No changes to commit"
        git push 